### ISSUE TITLE
Bug in timeZoneFromSeries

### ISSUE THREAD

**Issue by olafklinke** [ygale/timezone-series#20] opened 2022-08-31 07:57 UTC
I would expect the following to hold:
```
implies :: Bool -> Bool -> Bool
a `implies` b = not a || b 

(t > (fst.last.tzsTransitions) tzs) `implies` (timeZoneFromSeries tzs t ==  (snd.last.tzsTransitions) tzs)
```
That is, the last element of the `tzsTransitions` defines the `TimeZone` that is in effect at positive infinity, while the default `tzsTimeZone`  is the one in effect before the first change. Even if we construct a `TimeZoneSeries` with
```
(snd.last.tzsTransitions) tzs == tzsTimeZone tzs
```
(the last change switches back to default), the above invariant is violated. 
The docs say: "The default TimeZone object is used for times preceding the earliest UTCTime, or if the sequence of pairs is empty." which does not specify the behaviour after the last change. 

Code to reproduce below.
```
import Data.Time
import Data.Time.LocalTime.TimeZone.Series

-- central European time: UTC+1
cet = TimeZone {
    timeZoneMinutes = 60,
    timeZoneSummerOnly = False,
    timeZoneName = "CET"}

-- central European daylight savings time: UTC+2
cest = TimeZone {
    timeZoneMinutes = 120,
    timeZoneSummerOnly = True,
    timeZoneName = "CEST"}

-- change happens at last Sunday in March and October at 1:00 UTC
centralEurope :: TimeZoneSeries
centralEurope = TimeZoneSeries {
    tzsTimeZone = cet,
    tzsTransitions = [
        (UTCTime (fromGregorian 2021  3 28) (secondsToDiffTime 3600),cest),
        (UTCTime (fromGregorian 2021 10 31) (secondsToDiffTime 3600),cet)]
}

t1 = addUTCTime 3900 $ (fst.last.tzsTransitions) centralEurope

implies :: Bool -> Bool -> Bool
implies a b = not a || b

-- This is violated! invariantPlusInfinity t1 centralEurope == False
invariantPlusInfinity :: UTCTime -> TimeZoneSeries -> Bool
invariantPlusInfinity t tzs = (t > (fst.last.tzsTransitions) tzs) `implies` (timeZoneFromSeries tzs t ==  (snd.last.tzsTransitions) tzs)
```

**Comment by ygale** [comment] 2022-09-05 07:52
@olafklinke Please note the following from the haddocks for the `TimeZoneSeries` type:
> The times in the sequence are in order from latest to earlist

So your example is not a valid series.

For the same reason, your invariant is not correct - you should replace `last` by `head` in both places.

The expected behavior of timeZoneFromSeries for such a series is to ignore all transitions that are invalid because they are not earlier than all preceding transitions in the series. So your code sample is behaving as expected.

I am closing, because I don't see any issue so far. Please let me know if you feel we should reopen.

**Closed as completed by ygale** 2022-09-05 07:52 UTC

**Comment by olafklinke** [comment] 2022-09-05 12:11
Indeed, reversing the `tzsTransitions`  and replacing `last` by `head` makes `invariantPlusInfinity` true. I neglected that crucial sentence in the documentation.
